### ISSUE TITLE
fine-tune

### ISSUE THREAD

**Issue by Mian2001** [mlpc-ucsd/TokenCompose#10]
For fine-tuning Stable Diffusion v1.4, around which step does it typically converge? This information would be helpful for my further research work.

**Comment by JamesSand** [comment]
Hi
As indicate [here](https://github.com/mlpc-ucsd/TokenCompose/blob/5633f816116fdf7de74d9055ff9666c5222416e2/train/train.sh#L20), according to our experiments, SD 1.4 converges around 24500 steps.

**Comment by Mian2001** [comment]
Thank you for your response. I mean the fine-tuned SD v1.4, without using TokenCompose. Does it also converge at 24,500 steps?

**Comment by JamesSand** [comment]
We are not sure about for the convergence step for just finetuning SD 1.4. 
From our side, we first find SD 1.4 finetune with Tokencompose will converge at 24500 steps. So, in our paper, we also choose 24500 to finetune SD 1.4 without Tokencompose.

**Comment by Mian2001** [comment]
OK, thank you.
