### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by chmxu** [mlpc-ucsd/TokenCompose#4]
Hi, thank you for this great work. I wonder which gpu did you use in your experiments? I'm having OOM on V100 when the unet is equipped with the controller.

**Comment by chmxu** [comment]
NVM. I figure out I'm using 1024*1024 resolution, so the attention maps are larger too. Still it may save memory if (1) only cross attention maps are stored, (2) head-wise mean is done before storing the attn maps.

**Comment by zwcolin** [comment]
Hi Chengming,

Thanks for the suggestions! 

For the training setup -- we use RTX 3090 to train SD 1.4 (at 512\*512 res) and RTX A6000 to train SD 2.1 (at 768\*768 res). Let us know if you have any additional questions.
